


spring:
  main:
    banner-mode: "off"
    log-startup-info: "false"
  application:
    name: "campervan"


init_config:
instances:
  - jvm_direct: true
    port: 8085
    conf:
      - include:
          bean:
            - java.lang:type=MemoryPool,name=Metaspace
          attribute:
            Usage.used:
              metric_type: gauge
              alias: sb.usage.used